# ===========================================
# SPECTRUM JEKYLL THEME - MAIN CONFIGURATION
# ===========================================

# Jekyll Core Settings
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: UTC

# Site Identity
site:
  title: "Duhyeon Kim"
  description: "Personal website showcasing tech insights and development journey"
  url: "https://yoursite.com"
  baseurl: ""
  author: "Duhyeon Kim"
  email: "your@email.com"

# Personal Information
personal:
  name: "Duhyeon Kim"
  tagline: "spectrum jekyll owner"
  bio: "Developer passionate about technology, design, and continuous learning"
  location: "Seoul, Korea"

# Social Media Links
social:
  enabled: true
  platforms:
    email:
      enabled: true
      url: "kdhluck@naver.com"
      label: "Email"
      icon: "fa-solid fa-envelope"
    github:
      enabled: true
      url: "https://github.com/dudududukim"
      label: "GitHub"
      icon: "fa-brands fa-github"
    linkedin:
      enabled: true
      url: "https://www.linkedin.com/in/duhyeon-kim-6623082b1/"
      label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
    twitter:
      enabled: false
      url: "https://twitter.com/username"
      label: "Twitter"
      icon: "fa-brands fa-twitter"
    instagram:
      enabled: false
      url: "https://instagram.com/username"
      label: "Instagram"
      icon: "fa-brands fa-instagram"

# Accessibility Configuration
accessibility:
  skip_links: true
  focus_indicators: true
  screen_reader_text: "Skip to main content"
  high_contrast_mode: false
  reduced_motion: false

# Navigation Configuration
navigation:
  home_text: "Home"
  show_social: true
  social_position: "right"

# Footer Configuration
footer:
  copyright_text: "All rights reserved."
  show_theme_credit: true
  theme_name: "Spectrum"
  theme_url: "https://github.com/dudududukim/spectrum"

# Content Configuration
content:
  pages:
    about:
      title: "About"
      welcome_message: "Welcome 🤗"
      intro_text: "I'm Duhyeon Kim, an Electrical and Electronic Engineering major from Korea University. I have a broad curiosity about all things AI, and I enjoy diving deep into areas where I can focus and grow."
      main_description: "My hope is that, even if just a little, the path I take will leave something valuable for humanity. My dreams are big, but I'm still figuring out how to make them a reality."
      sections:
        - title: "Areas of Study & Work"
          content: "Here are a few topics I've studied or worked on:\n\n- Computer vision / NLP\n- FPGA & VLSI\n- Computer architecture"
      closing_text: "🌈 Wishing everyone a wonderful day!"
    
    tech_bites:
      title: "Tech Bites"
      description: "Daily tech insights and discoveries"
      list_page:
        welcome_message: "Welcome to my collection of tech insights!"
        intro_text: "Here you'll find bite-sized posts covering everything from JavaScript tips to performance optimization techniques, accessibility best practices, and modern web development workflows."
        description: "Each post is designed to be a quick read while providing practical, actionable information that you can apply to your own projects. Whether you're a seasoned developer or just starting out, there's something here for everyone."
        categories_title: "Categories"
        categories:
          - name: "JavaScript"
            description: "Modern ES6+ features, frameworks, and best practices"
          - name: "CSS"
            description: "Layout techniques, animations, and responsive design"
          - name: "Performance"
            description: "Optimization strategies and Core Web Vitals"
          - name: "Accessibility"
            description: "Building inclusive web experiences"
          - name: "Development"
            description: "Workflows, tools, and productivity tips"
        closing_text: "Browse through the posts below, or use the category filter to find content that interests you most."
      card:
        read_more_text: "Read More"
        min_read_text: "min read"
      navigation:
        previous_text: "← Previous"
        next_text: "Next →"
    
    films:
      title: "Films"
      description: "Photography collection showcasing moments captured through the lens"
  
  ui:
    buttons:
      view_all_tech_bites: "View All Tech Bites"
      read_more: "Read More"
    
    pagination:
      showing_text: "Showing"
      of_text: "of"
      tech_bites_text: "tech bites"
      page_text: "Page"
      previous_text: "Previous"
      next_text: "Next"
    
    error:
      404:
        title: "Page Not Found"
        message: "Sorry, the page you're looking for doesn't exist."
        suggestion: "You might want to go back to the homepage or check out our tech bites."
        back_home_text: "Back to Home"

# Theme Configuration (consolidated from theme.yml)
site_theme:
  colors:
    primary: "#3498db"
    secondary: "#2c3e50"
    accent: "#e74c3c"
    background: "#ffffff"
    text: "#2c3e50"
    light_text: "#7f8c8d"
    success: "#27ae60"
    warning: "#f39c12"
    error: "#e74c3c"
    info: "#3498db"
  
  typography:
    font_family: "Lato"
    font_weights:
      light: 300
      normal: 400
      medium: 500
      bold: 700
    font_sizes:
      xs: "0.75rem"
      sm: "0.875rem"
      base: "1rem"
      lg: "1.125rem"
      xl: "1.25rem"
      "2xl": "1.5rem"
      "3xl": "1.875rem"
      "4xl": "2.25rem"
  
  layout:
    max_width: "1125px"
    content_width: "875px"
    breakpoints:
      mobile: "768px"
      tablet: "1024px"
      desktop: "1200px"
  
  animations:
    enabled: true
    duration: "0.3s"
    easing: "ease"
    reduced_motion: false
  
  dark_mode:
    enabled: true
    auto_detect: true
    toggle_enabled: true
  
  components:
    cards:
      border_radius: "0.75rem"
      shadow: "0 4px 6px rgba(0, 0, 0, 0.1)"
      hover_shadow: "0 8px 25px rgba(0, 0, 0, 0.15)"
    buttons:
      border_radius: "0.5rem"
      padding: "0.75rem 1.5rem"
      transition: "all 0.3s ease"
    navigation:
      height: "4rem"
      background: "var(--bg-color)"
      border_bottom: "1px solid var(--border-light)"
    footer:
      padding: "0.75rem 0"
      background: "var(--bg-color)"
      border_top: "1px solid var(--border-light)"
  
  accessibility:
    focus_ring: "2px solid var(--primary-color)"
    focus_offset: "2px"
    high_contrast: false
    reduced_motion: false
    skip_links: true

# Homepage Section Controls
homepage_sections:
  tech_bites_preview:
    enabled: true
    show_count: 5
    show_read_more_button: true
    custom_title: "Recent Tech Bites"  # Optional override
  
  films_preview:
    enabled: true
    show_count: 6
    show_view_all_button: true
    custom_title: "Recent Films"    # Optional override
    animation_duration: 60
  
  # Future extensibility
  papers_preview:
    enabled: false
    show_count: 3
  
  gallery_preview:
    enabled: false
    show_count: 8

# Design Customization (maintain current defaults)
design_options:
  tech_bite_cards:
    compact_mode: true          # Current ultra-compact design
    show_excerpts: true
    show_reading_time: true
    max_excerpt_length: 150
  
  gallery_track:
    auto_scroll: true
    scroll_speed: 60           # Current animation duration
    show_overlay_on_hover: true
    
  navigation:
    fixed_position: true
    show_breadcrumbs: true
    social_position: "right"   # Current position
  
  footer:
    show_theme_credit: true    # Current setting
    compact_layout: true       # Current design

# Section Configuration
sections:
  tech_bite:
    enabled: true
    main_page_count: 5
    show_categories: true
    show_dates: true
    pagination: 10
  
  gallery_track:
    enabled: true
    image_count: 6
    animation_duration: 60

# Collections
collections:
  tech-bites:
    output: true
    permalink: /tech-bites/:name/
  papers:
    output: true
    permalink: /papers/:name/
  gallery:
    output: true
    permalink: /gallery/:name/

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tech-bites"
    values:
      layout: "tech-bite"
      show_sidebar: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build Settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Sass Configuration
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - assets/css

# Kramdown Configuration
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false